# OpenOCD Tcl: bring up a Zynq-7000 bare-metal program over JTAG.
# Sourced by host/mac/program.sh after board/digilent_zedboard.cfg.
#
# The order mirrors what Vitis's "Run on Hardware" does:
#   1. halt the ARM
#   2. load the bitstream into the fabric (pld load, via the PL TAP)
#   3. run ps7_init: clocks, DDR, MIO -- generated by Vivado for THIS block
#      design; without it the ARM has no working DDR to load code into
#   4. load the ELF into DDR, set PC to its entry point, resume
#
# ps7_init.tcl (from the .xsa) is written for Xilinx's xsct shell. It calls
# mwr / mrd / mask_write, defines its own mask_poll / mask_delay on top of
# mrd, and calls configparams. The shims below make OpenOCD look enough like
# xsct that the file runs unmodified. Key detail: xsct's mrd returns a
# STRING like "F8007080:   00000000" and ps7_init slices the last 8 hex
# digits off it -- so our mrd must return the same shape.

proc mwr {args} {
    set a [lindex $args end-1]; set v [lindex $args end]
    mww $a $v
}
proc mrd {args} {
    set a [lindex $args end]
    # ps7_init slices "0x[string range [mrd $addr] end-8 end]" -- 9 chars.
    # xsct's mrd output ends with the 8 hex digits AND a newline, so the
    # slice is 8 digits + "\n", which Tcl's expr trims. Match that shape.
    set line [string trim [mdw $a]]
    set val [lindex [split $line " "] end]
    return [format "%08X:   %s\n" [expr {$a}] $val]
}
proc mask_write {addr mask val} {
    set cur "0x[string range [mrd $addr] end-8 end]"
    mww $addr [expr {($cur & ~$mask) | ($val & $mask)}]
}
proc configparams {args} { return 0 }
proc init_apu_pll_reset {} {}

proc zynq_program {ps7 bit elf entry} {
    init
    echo "== reset + halt =="
    targets zynq.cpu0
    # A plain `halt` times out if the cores are parked from a previous
    # session; asserting SRST first (the ZedBoard cfg wires it) gives a
    # fresh BootROM state that halts reliably.
    reset halt
    sleep 200

    echo "== bitstream: $bit =="
    pld load 0 $bit
    sleep 100

    echo "== ps7_init: $ps7 =="
    # Source at GLOBAL scope: ps7_init.tcl's top-level `set`s (silicon
    # version constants, APU_FREQ) must be globals for the `variable`
    # lookups inside its procs to find them.
    uplevel #0 [list source $ps7]
    ps7_init
    ps7_post_config

    echo "== load ELF: $elf  (entry $entry) =="
    load_image $elf
    resume $entry
    echo "== running. watch the UART. =="
}
