# OpenOCD Tcl: bring up a Zynq-7000 bare-metal program over JTAG.
# Sourced by host/mac/program.sh after board/digilent_zedboard.cfg.
#
# The order matters and mirrors what Vitis's "Run on Hardware" does:
#   1. halt the ARM
#   2. load the bitstream into the fabric (pld load, via the PL TAP)
#   3. run ps7_init: clocks, DDR, MIO -- generated by Vivado for THIS block
#      design; without it the ARM has no working DDR to load code into
#   4. load the ELF into DDR, set PC to its entry point, resume
#
# ps7_init.tcl from the .xsa defines procs ps7_init / ps7_post_config that
# use xsct's memory commands (mwr/mrd, mask_write, mask_poll, mask_delay).
# The shims below map them onto OpenOCD's mww/mdw so the file runs
# unmodified. entry is extracted from the ELF header by program.sh.

proc mwr {args} {
    set a [lindex $args end-1]; set v [lindex $args end]
    mww $a $v
}
proc mrd {args} {
    set a [lindex $args end]
    return [expr {"0x[lindex [split [string trim [mdw $a]] " "] end]"}]
}
proc mask_write {addr mask val} {
    set cur [mrd $addr]
    mww $addr [expr {($cur & ~$mask) | ($val & $mask)}]
}
proc mask_poll {addr mask} {
    for {set i 0} {$i < 100000} {incr i} {
        if {[expr {[mrd $addr] & $mask}] != 0} { return }
    }
    echo "WARN mask_poll timeout at [format 0x%08x $addr]"
}
proc mask_delay {addr del} { sleep $del }
proc mask_read {addr mask} { return [expr {[mrd $addr] & $mask}] }
proc init_apu_pll_reset {} {}

proc zynq_program {ps7 bit elf entry} {
    init
    echo "== halt =="
    targets zynq.cpu0
    halt
    sleep 100

    echo "== bitstream: $bit =="
    pld load 0 $bit
    sleep 100

    echo "== ps7_init: $ps7 =="
    source $ps7
    ps7_init
    ps7_post_config

    echo "== load ELF: $elf  (entry $entry) =="
    load_image $elf
    resume $entry
    echo "== running. watch the UART. =="
}
