// ============================================================================
// GENERATED FILE -- do not edit. Regenerate with:  python3 sim/gen_weight_vh.py
// ed_scatter.v with the transposed conv1 weight table INLINED, for synthesis.
// The AXIS testbench with ENGINE=1 instantiates this exact module.
// ============================================================================
// Event-driven scatter unit (M6, D0018), parameterised by K banks (D0017).
//
// Given ONE input spike address, add that spike's weight into the input
// accumulator I of every output neuron it touches. Nothing else.
//
//   decode a -> (ic, iy, ix)
//   for each output position (oy, ox) whose 3x3/stride-2/pad-1 window
//   contains (iy, ix)  -- at most a 2x2 block:
//       ky = iy - 2*oy + 1,  kx = ix - 2*ox + 1
//       for oc in 0, K, 2K, ... :                        (C_OUT/K iterations)
//           for j in 0..K-1  IN PARALLEL:                (K RMWs this cycle)
//               I[bank j][off(oc+j,oy,ox)] += W_T[ic][ky][kx][oc+j]
//
// Banking (D0017): channel oc lives in bank oc mod K at offset
// ((oc / K) * H_OUT + oy) * W_OUT + ox. For a fixed (oy,ox), channels
// oc..oc+K-1 land in K distinct banks, so the K RMWs never collide -- no
// arbiter, no stall. K=1 is the plain sequential loop (verified first);
// K=4 is the same code with the loop fanned out.
//
// The transposed weight table W_T[ic][ky][kx][oc] puts channels oc..oc+K-1
// at K consecutive bytes, so one K-wide word read feeds all K RMWs.
//
// I is the ACCUMULATOR (D0019). The sweep reads/zeroes it through i_addr,
// which takes a GOLDEN FLAT index and is translated to (bank, offset) here,
// so ed_conv_layer, the sweep and every testbench are K-agnostic.
//
// UNVERIFIED until sim/run_ed_scatter_tb.sh passes at the chosen K.

`default_nettype none

module ed_scatter_c1 #(
    parameter C_IN  = 2,  H_IN  = 34, W_IN  = 34,
    parameter C_OUT = 16, H_OUT = 17, W_OUT = 17,
    parameter K = 1,
    parameter WIDTH = 16,
    parameter WT_FILE = "sim/vectors/ed_c1_wt.hex",
    parameter IN_BITS = C_IN * H_IN * W_IN,
    parameter NEURONS = C_OUT * H_OUT * W_OUT,
    parameter BANK_N  = NEURONS / K              // neurons per bank
) (
    input  wire                        clk,
    input  wire                        rst,
    input  wire                        clear,

    input  wire                        spk_we,
    input  wire [$clog2(IN_BITS)-1:0]  spk_addr,
    output reg                         busy,

    // I access for the sweep / testbench, GOLDEN flat index
    input  wire [$clog2(NEURONS)-1:0]  i_addr,
    output wire signed [WIDTH-1:0]     i_rdata,     // registered read
    input  wire                        i_we,
    input  wire signed [WIDTH-1:0]     i_wdata
);

    // --- memories ---------------------------------------------------------
    // W_T as one byte-addressed ROM; the K-wide read is K parallel lookups
    // at consecutive addresses (a synthesis tool maps this onto a K-byte-wide
    // BRAM word; in simulation it is K reads).
    reg signed [7:0]        wt [0:C_IN*9*C_OUT-1];
    // W_T INLINED (generated by sim/gen_weight_vh.py): transposed conv1
    // table, 288 entries, address ((ic*3+ky)*3+kx)*C_OUT+oc. No $readmemh.
    initial begin
        wt[  0] = 8'hf7;
        wt[  1] = 8'hdf;
        wt[  2] = 8'hea;
        wt[  3] = 8'h1b;
        wt[  4] = 8'h1a;
        wt[  5] = 8'h1e;
        wt[  6] = 8'h06;
        wt[  7] = 8'hee;
        wt[  8] = 8'hdb;
        wt[  9] = 8'he0;
        wt[ 10] = 8'h0d;
        wt[ 11] = 8'he6;
        wt[ 12] = 8'hc4;
        wt[ 13] = 8'h22;
        wt[ 14] = 8'h2a;
        wt[ 15] = 8'he4;
        wt[ 16] = 8'h10;
        wt[ 17] = 8'h01;
        wt[ 18] = 8'h41;
        wt[ 19] = 8'hd9;
        wt[ 20] = 8'h4c;
        wt[ 21] = 8'h31;
        wt[ 22] = 8'h17;
        wt[ 23] = 8'hd4;
        wt[ 24] = 8'h19;
        wt[ 25] = 8'hbe;
        wt[ 26] = 8'h00;
        wt[ 27] = 8'hf4;
        wt[ 28] = 8'hd4;
        wt[ 29] = 8'he7;
        wt[ 30] = 8'hf2;
        wt[ 31] = 8'hcb;
        wt[ 32] = 8'hd8;
        wt[ 33] = 8'h22;
        wt[ 34] = 8'h19;
        wt[ 35] = 8'h02;
        wt[ 36] = 8'h42;
        wt[ 37] = 8'h33;
        wt[ 38] = 8'hed;
        wt[ 39] = 8'hda;
        wt[ 40] = 8'h44;
        wt[ 41] = 8'hf4;
        wt[ 42] = 8'h36;
        wt[ 43] = 8'h02;
        wt[ 44] = 8'h30;
        wt[ 45] = 8'h23;
        wt[ 46] = 8'he2;
        wt[ 47] = 8'ha9;
        wt[ 48] = 8'hcf;
        wt[ 49] = 8'h2f;
        wt[ 50] = 8'h28;
        wt[ 51] = 8'hc9;
        wt[ 52] = 8'h3e;
        wt[ 53] = 8'h1a;
        wt[ 54] = 8'h2d;
        wt[ 55] = 8'hd5;
        wt[ 56] = 8'hed;
        wt[ 57] = 8'he8;
        wt[ 58] = 8'h16;
        wt[ 59] = 8'h28;
        wt[ 60] = 8'hbe;
        wt[ 61] = 8'hdb;
        wt[ 62] = 8'hce;
        wt[ 63] = 8'h18;
        wt[ 64] = 8'he6;
        wt[ 65] = 8'h08;
        wt[ 66] = 8'h01;
        wt[ 67] = 8'hc9;
        wt[ 68] = 8'h1d;
        wt[ 69] = 8'hdf;
        wt[ 70] = 8'hf5;
        wt[ 71] = 8'hea;
        wt[ 72] = 8'hc2;
        wt[ 73] = 8'hd5;
        wt[ 74] = 8'h23;
        wt[ 75] = 8'hcc;
        wt[ 76] = 8'hf2;
        wt[ 77] = 8'hfb;
        wt[ 78] = 8'hc2;
        wt[ 79] = 8'hde;
        wt[ 80] = 8'h26;
        wt[ 81] = 8'h3b;
        wt[ 82] = 8'he5;
        wt[ 83] = 8'hc1;
        wt[ 84] = 8'hd9;
        wt[ 85] = 8'hdc;
        wt[ 86] = 8'h2d;
        wt[ 87] = 8'hff;
        wt[ 88] = 8'hb8;
        wt[ 89] = 8'h11;
        wt[ 90] = 8'h22;
        wt[ 91] = 8'hb5;
        wt[ 92] = 8'h3b;
        wt[ 93] = 8'h15;
        wt[ 94] = 8'hf8;
        wt[ 95] = 8'hbc;
        wt[ 96] = 8'h07;
        wt[ 97] = 8'hf2;
        wt[ 98] = 8'h05;
        wt[ 99] = 8'h1e;
        wt[100] = 8'hf5;
        wt[101] = 8'h28;
        wt[102] = 8'h33;
        wt[103] = 8'he1;
        wt[104] = 8'he4;
        wt[105] = 8'hba;
        wt[106] = 8'hec;
        wt[107] = 8'hf2;
        wt[108] = 8'h0d;
        wt[109] = 8'h12;
        wt[110] = 8'hd1;
        wt[111] = 8'h40;
        wt[112] = 8'h38;
        wt[113] = 8'h19;
        wt[114] = 8'hc2;
        wt[115] = 8'h0c;
        wt[116] = 8'hdc;
        wt[117] = 8'h0e;
        wt[118] = 8'hdf;
        wt[119] = 8'hfc;
        wt[120] = 8'hbd;
        wt[121] = 8'hfd;
        wt[122] = 8'hef;
        wt[123] = 8'h25;
        wt[124] = 8'h04;
        wt[125] = 8'h3e;
        wt[126] = 8'hcc;
        wt[127] = 8'hef;
        wt[128] = 8'h16;
        wt[129] = 8'h40;
        wt[130] = 8'hd1;
        wt[131] = 8'hcd;
        wt[132] = 8'hc9;
        wt[133] = 8'hd3;
        wt[134] = 8'he7;
        wt[135] = 8'h27;
        wt[136] = 8'hcf;
        wt[137] = 8'h34;
        wt[138] = 8'hd1;
        wt[139] = 8'he9;
        wt[140] = 8'hd9;
        wt[141] = 8'hea;
        wt[142] = 8'hd3;
        wt[143] = 8'h07;
        wt[144] = 8'h06;
        wt[145] = 8'hd2;
        wt[146] = 8'he0;
        wt[147] = 8'h1e;
        wt[148] = 8'h32;
        wt[149] = 8'he2;
        wt[150] = 8'h18;
        wt[151] = 8'hfd;
        wt[152] = 8'h32;
        wt[153] = 8'hf4;
        wt[154] = 8'h18;
        wt[155] = 8'h32;
        wt[156] = 8'h26;
        wt[157] = 8'h13;
        wt[158] = 8'h28;
        wt[159] = 8'h14;
        wt[160] = 8'hfd;
        wt[161] = 8'hf3;
        wt[162] = 8'h21;
        wt[163] = 8'h25;
        wt[164] = 8'h30;
        wt[165] = 8'h40;
        wt[166] = 8'h09;
        wt[167] = 8'h05;
        wt[168] = 8'h2e;
        wt[169] = 8'h3d;
        wt[170] = 8'h31;
        wt[171] = 8'h20;
        wt[172] = 8'hde;
        wt[173] = 8'h19;
        wt[174] = 8'h28;
        wt[175] = 8'h03;
        wt[176] = 8'hfb;
        wt[177] = 8'hf8;
        wt[178] = 8'h1c;
        wt[179] = 8'hf8;
        wt[180] = 8'hd1;
        wt[181] = 8'h34;
        wt[182] = 8'h05;
        wt[183] = 8'hf5;
        wt[184] = 8'hc6;
        wt[185] = 8'h1e;
        wt[186] = 8'h32;
        wt[187] = 8'h10;
        wt[188] = 8'hf0;
        wt[189] = 8'h9f;
        wt[190] = 8'h39;
        wt[191] = 8'hd9;
        wt[192] = 8'hb8;
        wt[193] = 8'he9;
        wt[194] = 8'hee;
        wt[195] = 8'h14;
        wt[196] = 8'h0e;
        wt[197] = 8'hdc;
        wt[198] = 8'h27;
        wt[199] = 8'h20;
        wt[200] = 8'h3f;
        wt[201] = 8'hd5;
        wt[202] = 8'hd1;
        wt[203] = 8'h02;
        wt[204] = 8'hff;
        wt[205] = 8'h2c;
        wt[206] = 8'h22;
        wt[207] = 8'he6;
        wt[208] = 8'hd9;
        wt[209] = 8'h29;
        wt[210] = 8'h05;
        wt[211] = 8'h15;
        wt[212] = 8'hfe;
        wt[213] = 8'he3;
        wt[214] = 8'hfa;
        wt[215] = 8'h32;
        wt[216] = 8'hec;
        wt[217] = 8'h32;
        wt[218] = 8'h00;
        wt[219] = 8'h01;
        wt[220] = 8'h05;
        wt[221] = 8'hc9;
        wt[222] = 8'hff;
        wt[223] = 8'h39;
        wt[224] = 8'hdf;
        wt[225] = 8'hd9;
        wt[226] = 8'h31;
        wt[227] = 8'h24;
        wt[228] = 8'h02;
        wt[229] = 8'hae;
        wt[230] = 8'hcf;
        wt[231] = 8'h3a;
        wt[232] = 8'hf8;
        wt[233] = 8'h03;
        wt[234] = 8'he6;
        wt[235] = 8'h0e;
        wt[236] = 8'hfe;
        wt[237] = 8'he7;
        wt[238] = 8'h03;
        wt[239] = 8'h15;
        wt[240] = 8'h0e;
        wt[241] = 8'hde;
        wt[242] = 8'h2f;
        wt[243] = 8'h3b;
        wt[244] = 8'he6;
        wt[245] = 8'hfe;
        wt[246] = 8'h24;
        wt[247] = 8'h25;
        wt[248] = 8'h00;
        wt[249] = 8'hf4;
        wt[250] = 8'hd4;
        wt[251] = 8'he7;
        wt[252] = 8'h37;
        wt[253] = 8'hf9;
        wt[254] = 8'h17;
        wt[255] = 8'h36;
        wt[256] = 8'h26;
        wt[257] = 8'hc8;
        wt[258] = 8'h11;
        wt[259] = 8'hdb;
        wt[260] = 8'h14;
        wt[261] = 8'hb5;
        wt[262] = 8'hb9;
        wt[263] = 8'h3b;
        wt[264] = 8'h0f;
        wt[265] = 8'h3d;
        wt[266] = 8'hdc;
        wt[267] = 8'h05;
        wt[268] = 8'h0c;
        wt[269] = 8'hd7;
        wt[270] = 8'h34;
        wt[271] = 8'hfe;
        wt[272] = 8'h2a;
        wt[273] = 8'h9d;
        wt[274] = 8'h0e;
        wt[275] = 8'hee;
        wt[276] = 8'hdf;
        wt[277] = 8'he7;
        wt[278] = 8'hb3;
        wt[279] = 8'h06;
        wt[280] = 8'h02;
        wt[281] = 8'hd7;
        wt[282] = 8'h0f;
        wt[283] = 8'h0a;
        wt[284] = 8'h36;
        wt[285] = 8'h09;
        wt[286] = 8'h20;
        wt[287] = 8'h1d;
    end
    // K banks of the accumulator
    reg signed [WIDTH-1:0]  imem [0:K-1][0:BANK_N-1];

    // --- flat <-> (bank, offset) for the external port -------------------
    // flat = (oc*H_OUT + oy)*W_OUT + ox;  bank = oc % K;
    // offset = ((oc/K)*H_OUT + oy)*W_OUT + ox
    localparam HW = H_OUT * W_OUT;
    wire [31:0] p_oc  = i_addr / HW;
    wire [31:0] p_pos = i_addr % HW;
    wire [31:0] p_bank = p_oc % K;
    wire [31:0] p_off  = (p_oc / K) * HW + p_pos;

    reg signed [WIDTH-1:0] i_rdata_r;
    always @(posedge clk) i_rdata_r <= imem[p_bank][p_off];
    assign i_rdata = i_rdata_r;

    // --- decode the spike address -----------------------------------------
    reg [$clog2(IN_BITS)-1:0] a_r;
    integer ic, iy, ix;
    integer oy_lo, oy_hi, ox_lo, ox_hi;
    integer oy, ox, oc;
    reg     ic_wait;

    function integer lo_of(input integer i); begin lo_of = (i == 0) ? 0 : (i >> 1); end endfunction
    function integer hi_of(input integer i, input integer hmax);
        begin hi_of = ((i + 1) >> 1); if (hi_of > hmax - 1) hi_of = hmax - 1; end endfunction

    wire [1:0]  ky = iy - 2*oy + 1;
    wire [1:0]  kx = ix - 2*ox + 1;
    wire [31:0] wt_row = ((ic*3 + ky)*3 + kx)*C_OUT + oc;   // W_T[ic][ky][kx][oc..oc+K-1]
    // bank offset for channel oc+j at (oy,ox): ((oc+j)/K == oc/K since oc%K==0)
    wire [31:0] off_r = ((oc / K) * H_OUT + oy) * W_OUT + ox;

    // --- FSM --------------------------------------------------------------
    localparam S_IDLE = 0, S_DEC = 1, S_RD = 2, S_ADD = 3, S_NEXT = 4;
    reg [2:0] state;

    reg signed [7:0]       w_r [0:K-1];
    reg signed [WIDTH-1:0] i_r [0:K-1];
    reg [31:0]             off_hold;
    integer j, clr;

    always @(posedge clk) begin
        if (rst) begin
            state <= S_IDLE; busy <= 1'b0;
        end else case (state)

        S_IDLE: begin
            busy <= 1'b0;
            if (clear) begin
                clr <= 0; busy <= 1'b1; state <= S_NEXT;
            end else if (spk_we) begin
                a_r <= spk_addr; busy <= 1'b1; state <= S_DEC;
            end else if (i_we) begin
                imem[p_bank][p_off] <= i_wdata;             // sweep zeroing I
            end
        end

        S_DEC: begin
            ic <= a_r / (H_IN*W_IN);
            iy <= (a_r % (H_IN*W_IN)) / W_IN;
            ix <= a_r % W_IN;
            state <= S_RD; ic_wait <= 1'b1;
        end

        S_RD: begin
            if (ic_wait) begin
                oy_lo <= lo_of(iy); oy_hi <= hi_of(iy, H_OUT);
                ox_lo <= lo_of(ix); ox_hi <= hi_of(ix, W_OUT);
                oy <= lo_of(iy); ox <= lo_of(ix); oc <= 0;
                ic_wait <= 1'b0;
            end else begin
                // K-wide read: weights oc..oc+K-1 for this tap, and the K
                // accumulators they target -- one per bank, no conflicts
                for (j = 0; j < K; j = j + 1) begin
                    w_r[j] <= wt[wt_row + j];
                    i_r[j] <= imem[j][off_r];      // bank j holds channel oc+j
                end
                off_hold <= off_r;
                state <= S_ADD;
            end
        end

        S_ADD: begin   // K read-modify-writes, one per bank, this cycle
            for (j = 0; j < K; j = j + 1)
                imem[j][off_hold] <= i_r[j] + {{(WIDTH-8){w_r[j][7]}}, w_r[j]};
            if (oc + K < C_OUT) begin
                oc <= oc + K; state <= S_RD;
            end else begin
                oc <= 0;
                if (ox < ox_hi) begin ox <= ox + 1; state <= S_RD; end
                else begin
                    ox <= ox_lo;
                    if (oy < oy_hi) begin oy <= oy + 1; state <= S_RD; end
                    else state <= S_IDLE;
                end
            end
        end

        S_NEXT: begin  // clear: zero all banks, one offset per cycle
            for (j = 0; j < K; j = j + 1) imem[j][clr] <= 0;
            if (clr == BANK_N-1) state <= S_IDLE;
            else clr <= clr + 1;
        end

        endcase
    end

endmodule

`default_nettype wire
