"""Thesis tables generated from the repository's own files (never typed numbers).
Run: python3 docs/thesis_tables/make_tables.py   -> writes docs/thesis_tables/*.md
Data-derived tables: utilisation (Vivado power reports), ladder (check_all.sh),
vector sets (sim/vectors + runner geometry), RTL inventory (hdl/), quantisation
(golden npz + golden-check logs). The hand-written tables (timing_closure.md,
lessons.md) live beside them and are edited directly."""
import glob, os, re
import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "docs", "thesis_tables")
os.chdir(REPO)


def md_table(header, rows):
    return "| " + " | ".join(header) + " |\n|" + "---|" * len(header) + "\n" + "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows) + "\n"


# ---------------------------------------------------------------- utilisation and timing per silicon build
def utilisation():
    readme = open("experiments/power_estimates/README.md").read()
    est = {}
    for l in readme.splitlines():
        m = re.match(r"\| (\S+) \| (.*?) \| ([\d.]+) \| ([\d.]+) \|.*\| ([\d.]+) \|$", l)
        if m:
            est[m.group(1)] = (m.group(2), float(m.group(3)), float(m.group(4)), float(m.group(5)))
    passes = {}
    for l in open("experiments/silicon_ledger.md"):
        m = re.match(r"\| (\d+) \| [\d-]+ \| (\S+) \|", l)
        if m:
            passes[m.group(2)] = int(m.group(1))
    rows = []
    for rpt in sorted(glob.glob("experiments/power_estimates/*_power.rpt")):
        tag = os.path.basename(rpt)[:-len("_power.rpt")]
        if tag not in est or "superseded" in est[tag][0]:
            continue
        txt = open(rpt).read()
        g = lambda name: float(re.search(r"\|\s+%s\s+\|\s+[<\d.]+\s+\|\s+([\d.]+)\s+\|" % re.escape(name), txt).group(1))
        summ = open(rpt.replace("_power.rpt", "_summary.txt")).read()
        params = re.search(r"params\s+(.*)", summ).group(1)
        n = re.search(r"N_ENGINES=(\d+)", params).group(1)
        whs = re.search(r"WHS=([-\d.]+)", summ)
        lut = g("LUT as Logic") + g("LUT as Distributed RAM") + g("LUT as Shift Register")
        rows.append((passes.get(tag, "--"), tag, est[tag][0], n, "%.3f" % est[tag][1], whs.group(1)[:6] if whs else "--",
                     "%.0f (%.1f %%)" % (lut, 100 * lut / 53200), "%.0f (%.1f %%)" % (g("Register"), 100 * g("Register") / 106400),
                     "%.1f (%.1f %%)" % (g("Block RAM"), 100 * g("Block RAM") / 140), "0", "%.3f" % est[tag][2], "%.0f" % est[tag][3]))
    rows.sort(key=lambda r: (r[0] if isinstance(r[0], int) else 99, r[1]))
    hdr = ["pass", "build tag", "configuration", "N_ENGINES", "WNS (ns)", "WHS (ns)", "LUTs (of 53,200)", "FFs (of 106,400)", "BRAM tiles (of 140)", "DSP", "Vivado est. total (W)", "est. fabric (mW)"]
    open(os.path.join(OUT, "utilisation.md"), "w").write(
        "# Utilisation, timing and Vivado power estimate per silicon build\n\nGenerated by make_tables.py from experiments/power_estimates/*_power.rpt (post-route, whole design incl. wrapper and DMA; LUTs = logic + LUTRAM + SRL), *_summary.txt (WNS/WHS, parameters) and the README's estimate columns; pass numbers from experiments/silicon_ledger.md. Builds without a pass number were synthesised for the meter (C0019 strategy variants) but not run on the board.\n\n" + md_table(hdr, rows))
    return len(rows)


# ---------------------------------------------------------------- the verification ladder
def ladder():
    rows = []
    cls = lambda n, c: ("golden-model bit-identity" if any(k in n for k in ("vs golden", "engine", "conv", "FC", "neuron", "wrapper", "AXIS", "scatter", "I-dump", "corner")) else
                        "lint / synthesis safety" if "lint" in n.lower() else
                        "self-test (host, protocol, meter, robot loop)" if any(k in n for k in ("mock", "meter", "Y2", "selftest", "self")) else
                        "model check")
    i = 0
    for l in open("check_all.sh"):
        m = re.match(r'run\s+"([^"]+)"\s+(.*)', l)
        if m:
            i += 1
            cmd = m.group(2).strip()
            cmd = re.sub(r"bash -c '.*", "verilator --lint-only (see check_all.sh)", cmd)
            cmd = re.sub(r'python3 -c ".*', "python3 -c (inline; see check_all.sh)", cmd)
            rows.append((i, m.group(1), cls(m.group(1), cmd), "`" + cmd[:90] + "`"))
    open(os.path.join(OUT, "ladder.md"), "w").write(
        "# The verification ladder (check_all.sh)\n\nGenerated by make_tables.py from check_all.sh. Every check prints PASS or fails; the ladder is one command with one verdict (last full run: %d/%d). Comparison counts per check are printed by the checks themselves (e.g. 591,872 comparisons for ED c1 K=4; 1,048,576 for DVS-Gesture g1 through the AXIS wrapper) and belong in the caption, not here.\n\n" % (len(rows), len(rows))
        + md_table(["#", "check", "class", "command"], rows))
    return len(rows)


# ---------------------------------------------------------------- vector sets
def vector_sets():
    geo = {}
    for l in open("sim/run_ed_tb.sh"):
        m = re.match(r"\s+(\w+)\)\s+ci=(\d+);\s*hi=(\d+);\s*wi=(\d+);\s*co=(\d+);\s*ho=(\d+);\s*wo=(\d+)(?:;\s*ns=(\d+))?", l)
        if m:
            geo[m.group(1)] = m.groups()[1:7] + (m.group(8) or "16",)
    src = {"c1": ("N-MNIST C1", "golden/m1_weights_int8.npz", "check set, seeded (C0039)"), "c2": ("N-MNIST C2", "golden/m1_weights_int8.npz", "golden traces of C1 output"),
           "c3": ("N-MNIST C3", "golden/m1_weights_int8.npz", "golden traces of C2 output"), "g1": ("DVS-Gesture C1", "golden/dvsgesture_weights_int8.npz", "8 test clips"),
           "g2": ("DVS-Gesture C2", "golden/dvsgesture_weights_int8.npz", "golden traces of C1 output"), "g3": ("DVS-Gesture C3", "golden/dvsgesture_weights_int8.npz", "golden traces of C2 output"),
           "r1": ("robot C1 (recreation student)", "golden/r1_student_weights_int8.npz", "synthetic corner-activity frames (C0044 guard) or real frames with R1_REAL=1"),
           "i1": ("robot C1 (IsaacGym frames)", "robot/artifacts/fpga_student.pt", "64 teacher-driven event frames, repeated over T (direct coding)")}
    rows = []
    for L in ("c1", "c2", "c3", "g1", "g2", "g3", "r1", "i1"):
        ci, hi, wi, co, ho, wo, ns = geo.get(L, ("?",) * 7)
        thr = open("sim/vectors/%s_thresh.txt" % ("ed_" + L if os.path.exists("sim/vectors/ed_%s_thresh.txt" % L) else L)).read().strip() if (os.path.exists("sim/vectors/ed_%s_thresh.txt" % L) or os.path.exists("sim/vectors/%s_thresh.txt" % L)) else {"g1": "128", "c1": "64"}.get(L, "(runner default)")
        ef = [f for f in ("sim/vectors/ed_%s_exposure.txt" % L, "sim/vectors/%s_exposure.txt" % L) if os.path.exists(f)]
        exp = open(ef[0]).read().strip() if ef else "--"
        m = re.search(r"of (\d+)\): TL (\d+)\s+TR (\d+)\s+BL (\d+)\s+BR (\d+)", exp)
        expo = "TL %s / TR %s / BL %s / BR %s of %s frames" % (m.group(2), m.group(3), m.group(4), m.group(5), m.group(1)) if m else "--"
        blind = "BLIND at " + exp.split("BLIND at ")[1].split(" ")[0] if "BLIND" in exp else "all four corners exercised"
        rows.append((L, src[L][0], "%sx%sx%s -> %sx%sx%s" % (ci, hi, wi, co, ho, wo), ns, src[L][1], src[L][2], thr, expo, blind))
    open(os.path.join(OUT, "vector_sets.md"), "w").write(
        "# Test-vector sets and their corner exposure\n\nGenerated by make_tables.py from sim/run_ed_tb.sh (geometry, sample counts), sim/vectors/*_thresh.txt and *_exposure.txt (as last exported; the ladder regenerates them). Corner exposure = frames with at least one input spike in the receptive field of each corner output neuron (sim/corner_exposure.py, C0044): a set that is BLIND at a corner cannot catch a neuron-0-class bug there.\n\n"
        + md_table(["set", "layer", "geometry (C x H x W in -> out)", "samples", "weights", "inputs", "threshold 2^k", "corner exposure", "coverage"], rows))
    return len(rows)


# ---------------------------------------------------------------- RTL inventory
def rtl():
    role = {"lif_update.v": ("common", "the shared combinational LIF core (leak shift, pending subtract, compare)", "yes (in every engine)"),
            "lif_neuron.v": ("common", "M2 single-neuron wrapper around lif_update for the neuron testbench", "no (sim only)"),
            "conv_layer.v": ("dense", "M3 dense layer, P = 1 (superseded by conv_layer_p for silicon)", "pass 1-2 only"),
            "conv_layer_p.v": ("dense", "dense engine, P lanes, weight ROM, membrane and output-word banks", "yes"),
            "conv_layer_p_c1.v": ("dense", "conv_layer_p with the N-MNIST C1 weights baked in (generated)", "yes"),
            "conv_layer_p_g1.v": ("dense", "conv_layer_p with the DVS-Gesture C1 weights baked in (generated)", "yes"),
            "conv_layer_p_r1.v": ("dense", "conv_layer_p with the robot C1 weights baked in (generated)", "no (sim)"),
            "conv_layer_c1.v": ("dense", "P = 1 baked variant (historical)", "no"), "conv_layer_r1.v": ("dense", "P = 1 baked variant, robot (historical)", "no"),
            "fc_layer.v": ("dense", "dense FC layer (simulation, C0015)", "no (sim)"),
            "axis_conv.v": ("wrapper", "AXI-Stream wrapper: framing, ENGINE select, tick counter, replication", "yes"),
            "axis_conv_top.v": ("wrapper", "top: DATASET -> geometry/threshold localparams, engine instance", "yes"),
            "ed_conv_layer.v": ("event-driven", "ED engine: address list, scatter control, two-beat sweep pipeline, output words", "yes"),
            "ed_scatter.v": ("event-driven", "scatter unit: spike decode, weight-column fetch, K bank adders", "yes"),
            "ed_scatter_c1.v": ("event-driven", "ed_scatter with the N-MNIST C1 weights baked in (generated)", "yes"),
            "ed_scatter_g1.v": ("event-driven", "ed_scatter with the DVS-Gesture C1 weights baked in (generated)", "yes"),
            "ed_scatter_r1.v": ("event-driven", "ed_scatter with the robot C1 weights baked in (generated)", "no (sim)"),
            "ed_fc_layer.v": ("event-driven", "event-driven FC layer (D0023; simulation, C0015)", "no (sim)"),
            "ed_iface_shim.v": ("event-driven", "testbench shim presenting the scatter unit as a layer", "no (sim only)")}
    rows = []
    for f in sorted(glob.glob("hdl/*/*.v")):
        b = os.path.basename(f); n = sum(1 for _ in open(f))
        r = role.get(b, ("?", "", "?"))
        rows.append((f, n, r[0], r[1], r[2]))
    open(os.path.join(OUT, "rtl_inventory.md"), "w").write(
        "# RTL inventory\n\nGenerated by make_tables.py (line counts from hdl/; roles hand-maintained in the script). Generated baked variants come from sim/gen_weight_vh.py and are checked against the tracked npz by sim/check_baked_weights.py.\n\n"
        + md_table(["file", "lines", "group", "role", "on silicon"], rows) + "\nTotal: %d lines.\n" % sum(r[1] for r in rows))
    return len(rows)


# ---------------------------------------------------------------- quantisation per layer, per network on the board / in the ladder
def quantisation():
    nets = [("N-MNIST (seed 0, T=4)", "golden/m1_weights_int8.npz", sorted(glob.glob("experiments/*golden*seed0*.log")) or []),
            ("DVS-Gesture (seed 0, T=4)", "golden/dvsgesture_weights_int8.npz", sorted(glob.glob("experiments/dvsgesture/golden_check_seed0.log"))),
            ("robot student r1 (recreation)", "golden/r1_student_weights_int8.npz", [])]
    rows = []
    for name, npz, logs in nets:
        d = np.load(npz)
        rng = {}
        if logs:
            txt = open(logs[-1]).read()
            for m in re.finditer(r"(c1|c2|c3|fc)\s+V in \[\s*(-?\d+),\s*(-?\d+)\]", txt):
                lo, hi = int(m.group(2)), int(m.group(3)); rng[m.group(1)] = "%d..%d (%.0f %% of int16)" % (lo, hi, 100 * max(hi / 32767, -lo / 32768))
        for layer, key in (("C1", "conv1"), ("C2", "conv2"), ("C3", "conv3"), ("FC", "fc")):
            if key not in d.files:
                continue
            k = int(d[key + "_k"]); w = d[key]
            clip = float(d[key + "_clip_frac"]) if key + "_clip_frac" in d.files else 0.0
            rows.append((name, layer, "x".join(str(x) for x in w.shape), k, "2^-%d" % k, 2 ** k, "%.3f %%" % (100 * clip), int(np.abs(w).max()), rng.get(key.replace("conv", "c"), "--")))
    open(os.path.join(OUT, "quantisation.md"), "w").write(
        "# Quantisation per layer\n\nGenerated by make_tables.py from the tracked int8 weight files (golden/*.npz: shift k per layer, threshold 2^k, clip fraction) and the golden-check logs where present (membrane range over the check run). Weights are int8 at scale 2^-k; the integer threshold equals 2^k so a unit float threshold maps to the same scale; the FC folds the 2x2 pool's /4 into k+2 (D0004, D0008).\n\n"
        + md_table(["network", "layer", "weight shape", "k", "scale", "threshold", "clipped weights", "max |int8|", "membrane range (golden check)"], rows))
    return len(rows)


if __name__ == "__main__":
    for fn in (utilisation, ladder, vector_sets, rtl, quantisation):
        try:
            print("%-14s %d rows" % (fn.__name__, fn()))
        except Exception as e:
            print("FAILED", fn.__name__, repr(e))
