"""Thesis tables generated from the repository's own files (never typed numbers).
Run: python3 docs/thesis_tables/make_tables.py   -> writes docs/thesis_tables/*.md
Data-derived tables: utilisation (Vivado power reports), ladder (check_all.sh),
vector sets (sim/vectors + runner geometry), RTL inventory (hdl/), quantisation
(golden npz + golden-check logs). The hand-written tables (timing_closure.md,
lessons.md) live beside them and are edited directly."""
import glob, os, re
import numpy as np


def cycles_file(path):
    return np.array([int(l.split()[1]) for l in open(path) if not l.startswith('#')])


def dense_cycles(path):
    return int(re.search(r'(\d+) engine cycles', open(path).read()).group(1))

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "docs", "thesis_tables")
os.chdir(REPO)


def md_table(header, rows):
    return "| " + " | ".join(header) + " |\n|" + "---|" * len(header) + "\n" + "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows) + "\n"


# ---------------------------------------------------------------- utilisation and timing per silicon build
def utilisation():
    readme = open("experiments/power_estimates/README.md").read()
    est = {}
    for l in readme.splitlines():
        m = re.match(r"\| (\S+) \| (.*?) \| ([\d.]+) \| ([\d.]+) \|.*\| ([\d.]+) \|$", l)
        if m:
            est[m.group(1)] = (m.group(2), float(m.group(3)), float(m.group(4)), float(m.group(5)))
    passes = {}
    for l in open("experiments/silicon_ledger.md"):
        m = re.match(r"\| (\d+) \| [\d-]+ \| (\S+) \|", l)
        if m:
            passes[m.group(2)] = int(m.group(1))
    rows = []
    for rpt in sorted(glob.glob("experiments/power_estimates/*_power.rpt")):
        tag = os.path.basename(rpt)[:-len("_power.rpt")]
        if tag not in est or "superseded" in est[tag][0]:
            continue
        txt = open(rpt).read()
        g = lambda name: float(re.search(r"\|\s+%s\s+\|\s+[<\d.]+\s+\|\s+([\d.]+)\s+\|" % re.escape(name), txt).group(1))
        summ = open(rpt.replace("_power.rpt", "_summary.txt")).read()
        params = re.search(r"params\s+(.*)", summ).group(1)
        n = re.search(r"N_ENGINES=(\d+)", params).group(1)
        whs = re.search(r"WHS=([-\d.]+)", summ)
        lut = g("LUT as Logic") + g("LUT as Distributed RAM") + g("LUT as Shift Register")
        rows.append((passes.get(tag, "--"), tag, est[tag][0], n, "%.3f" % est[tag][1], whs.group(1)[:6] if whs else "--",
                     "%.0f (%.1f %%)" % (lut, 100 * lut / 53200), "%.0f (%.1f %%)" % (g("Register"), 100 * g("Register") / 106400),
                     "%.1f (%.1f %%)" % (g("Block RAM"), 100 * g("Block RAM") / 140), "0", "%.3f" % est[tag][2], "%.0f" % est[tag][3]))
    rows.sort(key=lambda r: (r[0] if isinstance(r[0], int) else 99, r[1]))
    hdr = ["pass", "build tag", "configuration", "N_ENGINES", "WNS (ns)", "WHS (ns)", "LUTs (of 53,200)", "FFs (of 106,400)", "BRAM tiles (of 140)", "DSP", "Vivado est. total (W)", "est. fabric (mW)"]
    open(os.path.join(OUT, "utilisation.md"), "w").write(
        "# Utilisation, timing and Vivado power estimate per silicon build\n\nGenerated by make_tables.py from experiments/power_estimates/*_power.rpt (post-route, whole design incl. wrapper and DMA; LUTs = logic + LUTRAM + SRL), *_summary.txt (WNS/WHS, parameters) and the README's estimate columns; pass numbers from experiments/silicon_ledger.md. Builds without a pass number were synthesised for the meter (C0019 strategy variants) but not run on the board.\n\n" + md_table(hdr, rows))
    return len(rows)


# ---------------------------------------------------------------- the verification ladder
def ladder():
    rows = []
    cls = lambda n, c: ("golden-model bit-identity" if any(k in n for k in ("vs golden", "engine", "conv", "FC", "neuron", "wrapper", "AXIS", "scatter", "I-dump", "corner")) else
                        "lint / synthesis safety" if "lint" in n.lower() else
                        "self-test (host, protocol, meter, robot loop)" if any(k in n for k in ("mock", "meter", "Y2", "selftest", "self")) else
                        "model check")
    i = 0
    for l in open("check_all.sh"):
        m = re.match(r'run\s+"([^"]+)"\s+(.*)', l)
        if m:
            i += 1
            cmd = m.group(2).strip()
            cmd = re.sub(r"bash -c '.*", "verilator --lint-only (see check_all.sh)", cmd)
            cmd = re.sub(r'python3 -c ".*', "python3 -c (inline; see check_all.sh)", cmd)
            rows.append((i, m.group(1), cls(m.group(1), cmd), "`" + cmd[:90] + "`"))
    open(os.path.join(OUT, "ladder.md"), "w").write(
        "# The verification ladder (check_all.sh)\n\nGenerated by make_tables.py from check_all.sh. Every check prints PASS or fails; the ladder is one command with one verdict (last full run: %d/%d). Comparison counts per check are printed by the checks themselves (e.g. 591,872 comparisons for ED c1 K=4; 1,048,576 for DVS-Gesture g1 through the AXIS wrapper) and belong in the caption, not here.\n\n" % (len(rows), len(rows))
        + md_table(["#", "check", "class", "command"], rows))
    return len(rows)


# ---------------------------------------------------------------- vector sets
def vector_sets():
    geo = {}
    for l in open("sim/run_ed_tb.sh"):
        m = re.match(r"\s+(\w+)\)\s+ci=(\d+);\s*hi=(\d+);\s*wi=(\d+);\s*co=(\d+);\s*ho=(\d+);\s*wo=(\d+)(?:;\s*ns=(\d+))?", l)
        if m:
            geo[m.group(1)] = m.groups()[1:7] + (m.group(8) or "16",)
    src = {"c1": ("N-MNIST C1", "golden/m1_weights_int8.npz", "check set, seeded (C0039)"), "c2": ("N-MNIST C2", "golden/m1_weights_int8.npz", "golden traces of C1 output"),
           "c3": ("N-MNIST C3", "golden/m1_weights_int8.npz", "golden traces of C2 output"), "g1": ("DVS-Gesture C1", "golden/dvsgesture_weights_int8.npz", "8 test clips"),
           "g2": ("DVS-Gesture C2", "golden/dvsgesture_weights_int8.npz", "golden traces of C1 output"), "g3": ("DVS-Gesture C3", "golden/dvsgesture_weights_int8.npz", "golden traces of C2 output"),
           "r1": ("robot C1 (recreation student)", "golden/r1_student_weights_int8.npz", "synthetic corner-activity frames (C0044 guard) or real frames with R1_REAL=1"),
           "i1": ("robot C1 (IsaacGym frames)", "robot/artifacts/fpga_student.pt", "64 teacher-driven event frames, repeated over T (direct coding)")}
    rows = []
    for L in ("c1", "c2", "c3", "g1", "g2", "g3", "r1", "i1"):
        ci, hi, wi, co, ho, wo, ns = geo.get(L, ("?",) * 7)
        thr = open("sim/vectors/%s_thresh.txt" % ("ed_" + L if os.path.exists("sim/vectors/ed_%s_thresh.txt" % L) else L)).read().strip() if (os.path.exists("sim/vectors/ed_%s_thresh.txt" % L) or os.path.exists("sim/vectors/%s_thresh.txt" % L)) else {"g1": "128", "c1": "64"}.get(L, "(runner default)")
        ef = [f for f in ("sim/vectors/ed_%s_exposure.txt" % L, "sim/vectors/%s_exposure.txt" % L) if os.path.exists(f)]
        exp = open(ef[0]).read().strip() if ef else "--"
        m = re.search(r"of (\d+)\): TL (\d+)\s+TR (\d+)\s+BL (\d+)\s+BR (\d+)", exp)
        expo = "TL %s / TR %s / BL %s / BR %s of %s frames" % (m.group(2), m.group(3), m.group(4), m.group(5), m.group(1)) if m else "--"
        blind = "BLIND at " + exp.split("BLIND at ")[1].split(" ")[0] if "BLIND" in exp else "all four corners exercised"
        rows.append((L, src[L][0], "%sx%sx%s -> %sx%sx%s" % (ci, hi, wi, co, ho, wo), ns, src[L][1], src[L][2], thr, expo, blind))
    open(os.path.join(OUT, "vector_sets.md"), "w").write(
        "# Test-vector sets and their corner exposure\n\nGenerated by make_tables.py from sim/run_ed_tb.sh (geometry, sample counts), sim/vectors/*_thresh.txt and *_exposure.txt (as last exported; the ladder regenerates them). Corner exposure = frames with at least one input spike in the receptive field of each corner output neuron (sim/corner_exposure.py, C0044): a set that is BLIND at a corner cannot catch a neuron-0-class bug there.\n\n"
        + md_table(["set", "layer", "geometry (C x H x W in -> out)", "samples", "weights", "inputs", "threshold 2^k", "corner exposure", "coverage"], rows))
    return len(rows)


# ---------------------------------------------------------------- RTL inventory
def rtl():
    role = {"lif_update.v": ("common", "the shared combinational LIF core (leak shift, pending subtract, compare)", "yes (in every engine)"),
            "lif_neuron.v": ("common", "M2 single-neuron wrapper around lif_update for the neuron testbench", "no (sim only)"),
            "conv_layer.v": ("dense", "M3 dense layer, P = 1 (superseded by conv_layer_p for silicon)", "pass 1-2 only"),
            "conv_layer_p.v": ("dense", "dense engine, P lanes, weight ROM, membrane and output-word banks", "yes"),
            "conv_layer_p_c1.v": ("dense", "conv_layer_p with the N-MNIST C1 weights baked in (generated)", "yes"),
            "conv_layer_p_g1.v": ("dense", "conv_layer_p with the DVS-Gesture C1 weights baked in (generated)", "yes"),
            "conv_layer_p_r1.v": ("dense", "conv_layer_p with the robot C1 weights baked in (generated)", "no (sim)"),
            "conv_layer_c1.v": ("dense", "P = 1 baked variant (historical)", "no"), "conv_layer_r1.v": ("dense", "P = 1 baked variant, robot (historical)", "no"),
            "fc_layer.v": ("dense", "dense FC layer (simulation, C0015)", "no (sim)"),
            "axis_conv.v": ("wrapper", "AXI-Stream wrapper: framing, ENGINE select, tick counter, replication", "yes"),
            "axis_conv_top.v": ("wrapper", "top: DATASET -> geometry/threshold localparams, engine instance", "yes"),
            "ed_conv_layer.v": ("event-driven", "ED engine: address list, scatter control, two-beat sweep pipeline, output words", "yes"),
            "ed_scatter.v": ("event-driven", "scatter unit: spike decode, weight-column fetch, K bank adders", "yes"),
            "ed_scatter_c1.v": ("event-driven", "ed_scatter with the N-MNIST C1 weights baked in (generated)", "yes"),
            "ed_scatter_g1.v": ("event-driven", "ed_scatter with the DVS-Gesture C1 weights baked in (generated)", "yes"),
            "ed_scatter_r1.v": ("event-driven", "ed_scatter with the robot C1 weights baked in (generated)", "no (sim)"),
            "ed_fc_layer.v": ("event-driven", "event-driven FC layer (D0023; simulation, C0015)", "no (sim)"),
            "ed_iface_shim.v": ("event-driven", "testbench shim presenting the scatter unit as a layer", "no (sim only)")}
    rows = []
    for f in sorted(glob.glob("hdl/*/*.v")):
        b = os.path.basename(f); n = sum(1 for _ in open(f))
        r = role.get(b, ("?", "", "?"))
        rows.append((f, n, r[0], r[1], r[2]))
    open(os.path.join(OUT, "rtl_inventory.md"), "w").write(
        "# RTL inventory\n\nGenerated by make_tables.py (line counts from hdl/; roles hand-maintained in the script). Generated baked variants come from sim/gen_weight_vh.py and are checked against the tracked npz by sim/check_baked_weights.py.\n\n"
        + md_table(["file", "lines", "group", "role", "on silicon"], rows) + "\nTotal: %d lines.\n" % sum(r[1] for r in rows))
    return len(rows)


# ---------------------------------------------------------------- quantisation per layer, per network on the board / in the ladder
def quantisation():
    nets = [("N-MNIST (seed 0, T=4)", "golden/m1_weights_int8.npz", sorted(glob.glob("experiments/*golden*seed0*.log")) or []),
            ("DVS-Gesture (seed 0, T=4)", "golden/dvsgesture_weights_int8.npz", sorted(glob.glob("experiments/dvsgesture/golden_check_seed0.log"))),
            ("robot student r1 (recreation)", "golden/r1_student_weights_int8.npz", [])]
    rows = []
    for name, npz, logs in nets:
        d = np.load(npz)
        rng = {}
        if logs:
            txt = open(logs[-1]).read()
            for m in re.finditer(r"(c1|c2|c3|fc)\s+V in \[\s*(-?\d+),\s*(-?\d+)\]", txt):
                lo, hi = int(m.group(2)), int(m.group(3)); rng[m.group(1)] = "%d..%d (%.0f %% of int16)" % (lo, hi, 100 * max(hi / 32767, -lo / 32768))
        for layer, key in (("C1", "conv1"), ("C2", "conv2"), ("C3", "conv3"), ("FC", "fc")):
            if key not in d.files:
                continue
            k = int(d[key + "_k"]); w = d[key]
            clip = float(d[key + "_clip_frac"]) if key + "_clip_frac" in d.files else 0.0
            rows.append((name, layer, "x".join(str(x) for x in w.shape), k, "2^-%d" % k, 2 ** k, "%.3f %%" % (100 * clip), int(np.abs(w).max()), rng.get(key.replace("conv", "c"), "--")))
    open(os.path.join(OUT, "quantisation.md"), "w").write(
        "# Quantisation per layer\n\nGenerated by make_tables.py from the tracked int8 weight files (golden/*.npz: shift k per layer, threshold 2^k, clip fraction) and the golden-check logs where present (membrane range over the check run). Weights are int8 at scale 2^-k; the integer threshold equals 2^k so a unit float threshold maps to the same scale; the FC folds the 2x2 pool's /4 into k+2 (D0004, D0008).\n\n"
        + md_table(["network", "layer", "weight shape", "k", "scale", "threshold", "clipped weights", "max |int8|", "membrane range (golden check)"], rows))
    return len(rows)


# ---------------------------------------------------------------- accuracy and firing rates per trained network
def _train_final(path):
    """(test acc, {c1,c2,c3,fc}) from a train log's last epoch line or a firing-rate CSV's last test row."""
    if path.endswith(".csv"):
        rows = [l.strip().split(",") for l in open(path) if l.strip() and not l.startswith("epoch")]
        r = [x for x in rows if x[1] == "test"][-1]
        return float(r[3]), dict(zip(("c1", "c2", "c3", "fc"), map(float, r[4:8])))
    last = None
    for l in open(path):
        m = re.match(r"epoch\s+(\d+).*test acc ([\d.]+).*c1=([\d.]+)\s+c2=([\d.]+)\s+c3=([\d.]+)\s+fc=([\d.]+)", l)
        if m:
            last = m
    return (float(last.group(2)), dict(zip(("c1", "c2", "c3", "fc"), map(float, last.groups()[2:])))) if last else (None, {})


def _golden(path):
    txt = open(path).read()
    f = re.search(r"float model\s*:\s*([\d.]+)%", txt); g = re.search(r"golden integer:\s*([\d.]+)%", txt)
    m = re.search(r"fc\s+V in \[\s*(-?\d+),\s*(-?\d+)\]", txt)
    pct = 100 * max(int(m.group(2)) / 32767, -int(m.group(1)) / 32768) if m else None
    return (float(f.group(1)) if f else None, float(g.group(1)) if g else None, pct)


def accuracy_rates():
    nets = []  # (dataset, network, seed, T, train source, golden log)
    nets.append(("N-MNIST", "baseline", 0, 4, "experiments/m0_firing_rates_binarised.csv", None))
    for T in (8, 16):
        for sd in (0, 1, 2):
            nets.append(("N-MNIST", "baseline", sd, T, "experiments/tsweep_nmnist/m0_firing_rates_binarised_nmnist_seed%d_t%d.csv" % (sd, T), "experiments/tsweep_nmnist/golden_t%d_seed%d.log" % (T, sd)))
    for r in ("0.02", "0.04", "0.08", "0.16", "0.30"):
        for sd in (0, 1, 2):
            sfx = "" if sd == 0 else "_seed%d" % sd
            nets.append(("N-MNIST", "rate target %s" % r, sd, 4, "experiments/rate_sweep/train_rate%s%s.log" % (r, sfx), "experiments/rate_sweep/golden_rate%s%s.log" % (r, sfx)))
            nets.append(("DVS-Gesture", "rate target %s" % r, sd, 4, "experiments/rate_sweep_dvsg/train_rate%s%s.log" % (r, sfx), "experiments/rate_sweep_dvsg/golden_rate%s%s.log" % (r, sfx)))
    for sd in (0, 1, 2):
        nets.append(("DVS-Gesture", "baseline", sd, 4, "experiments/dvsgesture/train_seed%d.log" % sd, "experiments/dvsgesture/golden_check_seed%d.log" % sd))
        for T in (8, 16):
            nets.append(("DVS-Gesture", "baseline", sd, T, "experiments/dvsgesture/t%d/train_seed%d.log" % (T, sd), "experiments/dvsgesture/t%d/golden_check_seed%d.log" % (T, sd)))
    rows = []
    for ds, net, sd, T, tr, gl in nets:
        if not os.path.exists(tr):
            continue
        acc, rates = _train_final(tr)
        fa, ga, pct = _golden(gl) if gl and os.path.exists(gl) else (None, None, None)
        fmt = lambda v: "--" if v is None else "%.2f" % v
        rows.append((ds, net, sd, T, fmt(100 * acc if acc is not None else None), fmt(ga), "--" if pct is None else ("%.0f %%" % pct + (" **overflow**" if pct > 100 else "")),
                     "%.3f / %.3f / %.3f / %.3f" % (rates["c1"], rates["c2"], rates["c3"], rates["fc"]) if rates else "--", os.path.relpath(tr)))
    rows.sort(key=lambda r: (r[0], r[1] != "baseline", r[1], r[3], r[2]))
    open(os.path.join(OUT, "accuracy_rates.md"), "w").write(
        "# Accuracy and firing rates per trained network\n\nGenerated by make_tables.py from the training logs / firing-rate CSVs (final-epoch test accuracy and per-layer test firing rates) and the golden-check logs (integer-model accuracy on the full test set; fc membrane use as % of int16). Rates are the fraction of neurons firing per timestep on the test set. A row without a golden column has no golden log in the repository.\n\n"
        + md_table(["dataset", "network", "seed", "T", "float test acc (%)", "golden integer acc (%)", "fc membrane (% of int16)", "rates c1 / c2 / c3 / fc", "source"], rows))
    return len(rows)


# ---------------------------------------------------------------- T sweep summary
def tsweep():
    groups = [("N-MNIST", 4, ["experiments/m0_firing_rates_binarised.csv"], []),
              ("N-MNIST", 8, [], glob.glob("experiments/tsweep_nmnist/golden_t8_seed*.log")),
              ("N-MNIST", 16, [], glob.glob("experiments/tsweep_nmnist/golden_t16_seed*.log")),
              ("DVS-Gesture", 4, [], glob.glob("experiments/dvsgesture/golden_check_seed*.log")),
              ("DVS-Gesture", 8, [], glob.glob("experiments/dvsgesture/t8/golden_check_seed*.log")),
              ("DVS-Gesture", 16, [], glob.glob("experiments/dvsgesture/t16/golden_check_seed*.log"))]
    rows = []
    for ds, T, csvs, logs in groups:
        fl, gl, pc = [], [], []
        for f in logs:
            a, b, c = _golden(f); fl.append(a); gl.append(b); pc.append(c)
        for f in csvs:
            fl.append(100 * _train_final(f)[0])
        ms = lambda v: "--" if not v else ("%.2f" % v[0] if len(v) == 1 else "%.2f +- %.2f" % (np.mean(v), np.std(v, ddof=1)))
        rows.append((ds, T, len(fl), ms([x for x in fl if x is not None]), ms([x for x in gl if x is not None]),
                     "--" if not pc else "%.0f-%.0f %%" % (min(pc), max(pc)), "--" if not pc else "%d of %d" % (sum(1 for x in pc if x > 100), len(pc))))
    open(os.path.join(OUT, "tsweep.md"), "w").write(
        "# Timesteps T vs accuracy and the int16 membrane ceiling\n\nGenerated by make_tables.py from the golden-check logs per (dataset, T, seed). Accuracy mean +- sd over seeds (sample sd); fc membrane use = peak |V| as a fraction of int16 over the golden run; a network 'overflows' when that exceeds 100 %% (the hardware membrane is int16, the golden model's is int32 -- see C0046). N-MNIST T=4 has no golden log with a membrane line in the repository; its float accuracy comes from the M0 CSV.\n\n"
        + md_table(["dataset", "T", "seeds", "float acc (%)", "golden integer acc (%)", "fc membrane (% of int16, min-max)", "overflowing seeds"], rows))
    return len(rows)


# ---------------------------------------------------------------- crossover table: every axis, layer, dataset, basis
def crossover():
    rows = []
    # parallelism axis, C1: fit ED(K) = a + b/K over K=1..16 and dense(P) = c/P (+ measured P=4 point), solve ED = dense
    for ds, d, extra in (("N-MNIST", "experiments/latency_sim/ksweep_c0035", {4: 104059}), ("DVS-Gesture", "experiments/dvsgesture/latency_sim", {})):
        Ks = [1, 2, 4, 8, 16]; ed = [cycles_file(os.path.join(d, "ed_k%d.txt" % k)).mean() for k in Ks]
        A = np.vstack([np.ones(5), 1.0 / np.array(Ks)]).T; a, b = np.linalg.lstsq(A, np.array(ed), rcond=None)[0]
        dn = dict(extra)
        for P in Ks:
            f = os.path.join(d, "dense_p%d.txt" % P)
            if os.path.exists(f):
                dn[P] = dense_cycles(f)
        Ps = sorted(dn); B = np.vstack([1.0 / np.array(Ps), np.ones(len(Ps))]).T; c, dd = np.linalg.lstsq(B, np.array([dn[p] for p in Ps]), rcond=None)[0]
        kk = np.linspace(1, 32, 3101); x = kk[np.argmin(np.abs((a + b / kk) - (c / kk + dd)))]
        rows.append(("parallelism (K = P)", "C1", ds, "--", "K = P = %.1f" % x, "sim (cycle-model fits: ED over K = 1..16, dense over the P points in the files)", "silicon: ED wins at 4, dense at 8 (N-MNIST)" if ds == "N-MNIST" else "silicon: ED wins 6/8 clips at K = P = 4", "ED = %.0f + %.0f/K; dense = %.0f/P + %.0f" % (a, b, c, dd)))
    # activity axis, C1 per clip (DVS-Gesture): threshold in input spikes from the README statement
    txt = open("experiments/dvsgesture/latency_sim/README.md").read()
    m = re.search(r"fewer than ~([\d,]+) spikes", txt)
    rows.append(("activity (per sample)", "C1", "DVS-Gesture", "K = P = 4", "< ~%s input spikes per inference (~30.5 %% density)" % (m.group(1) if m else "10,000"), "sim, pre-registered", "silicon: ED wins 6/8 clips, loses clips 1 and 5 (36 %, 44 %)", "clip densities 9-44 %"))
    # activity axis by training, C2/C3, from the per-K fits
    cfg = [("N-MNIST", "experiments/rate_sweep", "golden/traces_m1.npz", {"c2": ("c1_S", 16 * 17 * 17, "C2"), "c3": ("c2_S", 32 * 9 * 9, "C3")}),
           ("DVS-Gesture", "experiments/rate_sweep_dvsg", "golden/traces_dvsgesture.npz", {"g2": ("c1_S", 16 * 32 * 32, "C2"), "g3": ("c2_S", 32 * 16 * 16, "C3")})]
    tags = ["base", "0.02", "0.04", "0.08", "0.16", "0.30"]
    for ds, d, base_tr, layers in cfg:
        for L, (key, inbits, name) in layers.items():
            base_rate = None
            for K in (4, 8, 16):
                xs, ys = [], []
                for t in tags:
                    f = os.path.join(d, "bench", "ed_k%d_%s_%s.txt" % (K, t, L)); tr = base_tr if t == "base" else os.path.join(d, "traces_rate%s.npz" % t)
                    if os.path.exists(f) and os.path.exists(tr) and len(cycles_file(f)):
                        sp = int((np.load(tr)[key] != 0).sum()) / 16; xs.append(sp); ys.append(cycles_file(f).mean())
                        if t == "base": base_rate = 100 * sp / (4 * inbits)
                if len(xs) < 3:
                    continue
                A = np.vstack([np.ones(len(xs)), xs]).T; a, b = np.linalg.lstsq(A, np.array(ys), rcond=None)[0]
                dn = dense_cycles(os.path.join(d, "bench", "dense_p4_base_%s.txt" % L)) / (K / 4)
                cx = 100 * ((dn - a) / b) / (4 * inbits)
                rows.append(("activity (trained)", name, ds, "K = P = %d" % K, "%.0f %% input activity" % cx, "sim (6 networks, 16 samples each, fit ED = a + b s)",
                             "baseline network at %.1f %%: %s" % (base_rate, "ED wins" if base_rate < cx else "dense wins"), "a = %.0f, b = %.1f cycles/spike" % (a, b)))
    open(os.path.join(OUT, "crossover.md"), "w").write(
        "# Crossover table: every axis, layer and dataset\n\nGenerated by make_tables.py from experiments/latency_sim, experiments/dvsgesture/latency_sim and the rate-sweep bench files. 'Basis' says whether the number is a simulation fit or a silicon observation; the silicon column states what the board showed at the bracketing points. The operating point is the unregularised (baseline) network's input activity on the check set.\n\n"
        + md_table(["axis", "layer", "dataset", "at", "crossover", "basis", "operating point / silicon", "fit"], rows))
    return len(rows)


# ---------------------------------------------------------------- silicon passes with their predictions (from the ledger) and the record files
def passes():
    rows = []
    for l in open("experiments/silicon_ledger.md"):
        m = re.match(r"\| (\d+) \| ([\d-]+) \| (.*?) \| (.*?) \| (.*?) \| (\d+) \| ([+\-][\d.]+) \| (.*?) \| (.*?) \| (.*?) \| (.*?) \|", l)
        if m:
            rows.append(m.groups())
    open(os.path.join(OUT, "passes.md"), "w").write(
        "# Silicon passes 3-14 with pre-registration outcome\n\nGenerated by make_tables.py from experiments/silicon_ledger.md (which is maintained by the board session). Passes 1-2 (2026-08) were the loopback and first functional engine, superseded. Predicted latencies and their errors per sample are in each record file's own table (board vs sim columns); the 'prereg' column is the pre-registration verdict.\n\n"
        + md_table(["pass", "date (2026)", "build", "engine", "dataset", "N_ENGINES", "WNS (ns)", "bit-identical", "engine latency", "prereg", "record"], rows))
    return len(rows)


# ---------------------------------------------------------------- deadline projection from per-sample latency distributions
def deadline():
    sets = []
    f64 = "experiments/p1_distill/isaac_i1_ed_k4_cycles_64.txt"
    if os.path.exists(f64) and len(cycles_file(f64)):
        sets.append(("robot event frames (64, sim)", cycles_file(f64) / 100.0, 1441788 / 4 / 100.0))
    k8, k4 = [], []
    for l in open("experiments/board_ed_k8_20260917.md"):
        m = re.match(r"\| (\d+) \| \d \| ([\d.]+) \| ([\d.]+) \| \+[\d.]+ % \| ([\d.]+) \|", l)
        if m:
            k8.append(float(m.group(2))); k4.append(float(m.group(4)))
    sets.append(("N-MNIST C1 (16 samples, board, K = P = 4)", np.array(k4), 1048.9))
    sets.append(("N-MNIST C1 (16 samples, board, K = P = 8)", np.array(k8), 540.3))
    db = []
    for l in open("experiments/dvsgesture/board_ed_k4_20260919.md"):
        m = re.match(r"\| (\d) \| \d+ \| ([\d.]+) \| ([\d.]+) \|", l)
        if m:
            db.append(float(m.group(2)))
    sets.append(("DVS-Gesture C1 (8 clips, board, K = P = 4)", np.array(db), 3706.5))
    rows = []
    for name, ed, dn in sets:
        miss = lambda hz, arr: 100 * np.mean(arr > 1e6 / hz)
        rows.append((name, "ED", "%.0f" % ed.mean(), "%.0f" % ed.max(), "%.2fx" % (ed.max() / ed.min()), "%.1f %%" % (100 * ed.max() / 1e5), "%.0f Hz" % (1e6 / ed.max()),
                     " / ".join("%.0f" % miss(hz, ed) for hz in (10, 20, 50, 100, 200))))
        rows.append((name, "dense", "%.0f" % dn, "%.0f" % dn, "1.00x", "%.1f %%" % (100 * dn / 1e5), "%.0f Hz" % (1e6 / dn),
                     " / ".join("%.0f" % (100.0 if dn > 1e6 / hz else 0.0) for hz in (10, 20, 50, 100, 200))))
    open(os.path.join(OUT, "deadline.md"), "w").write(
        "# Deadline reading: per-sample latency distributions against perception periods\n\nGenerated by make_tables.py from the per-sample cycle/board files. 'Max sustainable rate' is the perception rate at which the WORST sample still meets its period (1 / worst latency, engine-only, no host or DMA time); miss rate at a given rate is the fraction of samples whose latency exceeds that period. The robot's control period is 100 ms (10 Hz), so the budget fraction column is worst latency / 100 ms. Both engines meet every period up to 200 Hz on every set; the difference between them appears only above that, and in the spread.\n\n"
        + md_table(["sample set", "engine", "mean (us)", "worst (us)", "spread max/min", "worst as % of 100 ms budget", "max sustainable rate", "miss rate % at 10 / 20 / 50 / 100 / 200 Hz"], rows))
    return len(rows)


if __name__ == "__main__":
    for fn in (utilisation, ladder, vector_sets, rtl, quantisation, accuracy_rates, tsweep, crossover, passes, deadline):
        try:
            print("%-14s %d rows" % (fn.__name__, fn()))
        except Exception as e:
            print("FAILED", fn.__name__, repr(e))
