"""Regenerate hdl/dense/weights/*.vh from golden/m1_weights_int8.npz.
Run:  python3 sim/gen_weight_vh.py
The .vh files bake the int8 weights into the RTL as an initial block, so
synthesis needs no $readmemh file lookup (a silent failure mode in Vivado)."""
import numpy as np, os
REPO=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
z=np.load(os.path.join(REPO,'golden','m1_weights_int8.npz'))
os.makedirs(os.path.join(REPO,'hdl','dense','weights'), exist_ok=True)
for key,name in (('conv1','conv1_w'),('conv2','conv2_w'),('conv3','conv3_w')):
    flat=z[key].ravel()
    lines=['// AUTO-GENERATED by sim/gen_weight_vh.py from golden/m1_weights_int8.npz (%s).' % key,
           '// Included by conv_layer.v when WEIGHT_FILE == "" -- weights baked into the RTL so',
           '// synthesis has NO file dependency ($readmemh path problems in Vivado are silent).',
           '// %d entries, address = ((oc*C_IN+ic)*3+ky)*3+kx, int8 two\'s complement.' % len(flat)]
    lines += ["    wrom[%5d] = 8'h%02x;" % (i, int(v)&0xFF) for i,v in enumerate(flat)]
    open(os.path.join(REPO,'hdl','dense','weights',name+'.vh'),'w').write('\n'.join(lines)+'\n')
    print('%s: %d entries' % (name, len(flat)))


# --- also emit the self-contained synthesis variant of conv_layer for c1 ---
def emit_inlined_conv1():
    src=open(os.path.join(REPO,'hdl','dense','conv_layer.v')).read()
    tab=open(os.path.join(REPO,'hdl','dense','weights','conv1_w.vh')).read()
    line='    initial $readmemh(WEIGHT_FILE, wrom);\n'
    gs=src.index(line); ge=gs+len(line)
    inl=('    // Weights INLINED (generated by sim/gen_weight_vh.py). No include, no\n'
         '    // $readmemh, no file path for Vivado to lose. Same values as the hex.\n'
         '    initial begin\n' + '\n'.join(l for l in tab.split('\n') if l.strip().startswith('wrom[')) + '\n    end\n')
    out=src[:gs]+inl+src[ge:]
    out=out.replace('module conv_layer #(','module conv_layer_c1 #(')
    # strip the WEIGHT_FILE/BAKED_WEIGHTS parameter block: this variant has no file path
    ps=out.index('    parameter WEIGHT_FILE = "sim/vectors/conv_c1_w.hex",')
    pe=out.index('    parameter IN_BITS  =')
    out=out[:ps]+'    // (no WEIGHT_FILE / BAKED_WEIGHTS: the conv1 table is inlined below)\n'+out[pe:]
    out=out.replace('// still uses $readmemh, which Vivado honours at synthesis if the hex file\n// is added as a project source.','// are INLINED in this generated variant -- nothing for synthesis to find.')
    hdr=('// ============================================================================\n'
         '// GENERATED FILE -- do not edit. Regenerate with:  python3 sim/gen_weight_vh.py\n'
         '// conv_layer.v with the conv1 weight table INLINED, for synthesis: no include,\n'
         '// no $readmemh, no file path for Vivado to lose. sim/run_axis_tb.sh\n'
         '// instantiates this exact module, so the table is verified against golden.\n'
         '// ============================================================================\n')
    open(os.path.join(REPO,'hdl','dense','conv_layer_c1.v'),'w').write(hdr+out)
    print('conv_layer_c1.v: inlined')
import re
emit_inlined_conv1()
