"""Regenerate hdl/dense/weights/*.vh from golden/m1_weights_int8.npz.
Run:  python3 sim/gen_weight_vh.py
The .vh files bake the int8 weights into the RTL as an initial block, so
synthesis needs no $readmemh file lookup (a silent failure mode in Vivado)."""
import numpy as np, os
REPO=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
z=np.load(os.path.join(REPO,'golden','m1_weights_int8.npz'))
os.makedirs(os.path.join(REPO,'hdl','dense','weights'), exist_ok=True)
for key,name in (('conv1','conv1_w'),('conv2','conv2_w'),('conv3','conv3_w')):
    flat=z[key].ravel()
    lines=['// AUTO-GENERATED by sim/gen_weight_vh.py from golden/m1_weights_int8.npz (%s).' % key,
           '// Included by conv_layer.v when WEIGHT_FILE == "" -- weights baked into the RTL so',
           '// synthesis has NO file dependency ($readmemh path problems in Vivado are silent).',
           '// %d entries, address = ((oc*C_IN+ic)*3+ky)*3+kx, int8 two\'s complement.' % len(flat)]
    lines += ["    wrom[%5d] = 8'h%02x;" % (i, int(v)&0xFF) for i,v in enumerate(flat)]
    open(os.path.join(REPO,'hdl','dense','weights',name+'.vh'),'w').write('\n'.join(lines)+'\n')
    print('%s: %d entries' % (name, len(flat)))
