"""Regenerate hdl/dense/weights/*.vh from golden/m1_weights_int8.npz.
Run:  python3 sim/gen_weight_vh.py
The .vh files bake the int8 weights into the RTL as an initial block, so
synthesis needs no $readmemh file lookup (a silent failure mode in Vivado)."""
import numpy as np, os
REPO=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
z=np.load(os.path.join(REPO,'golden','m1_weights_int8.npz'))
os.makedirs(os.path.join(REPO,'hdl','dense','weights'), exist_ok=True)
for key,name in (('conv1','conv1_w'),('conv2','conv2_w'),('conv3','conv3_w')):
    flat=z[key].ravel()
    lines=['// AUTO-GENERATED by sim/gen_weight_vh.py from golden/m1_weights_int8.npz (%s).' % key,
           '// Included by conv_layer.v when WEIGHT_FILE == "" -- weights baked into the RTL so',
           '// synthesis has NO file dependency ($readmemh path problems in Vivado are silent).',
           '// %d entries, address = ((oc*C_IN+ic)*3+ky)*3+kx, int8 two\'s complement.' % len(flat)]
    lines += ["    wrom[%5d] = 8'h%02x;" % (i, int(v)&0xFF) for i,v in enumerate(flat)]
    open(os.path.join(REPO,'hdl','dense','weights',name+'.vh'),'w').write('\n'.join(lines)+'\n')
    print('%s: %d entries' % (name, len(flat)))


# --- also emit the self-contained synthesis variant of conv_layer for c1 ---
def emit_inlined_conv1():
    src=open(os.path.join(REPO,'hdl','dense','conv_layer.v')).read()
    tab=open(os.path.join(REPO,'hdl','dense','weights','conv1_w.vh')).read()
    line='    initial $readmemh(WEIGHT_FILE, wrom);\n'
    gs=src.index(line); ge=gs+len(line)
    inl=('    // Weights INLINED (generated by sim/gen_weight_vh.py). No include, no\n'
         '    // $readmemh, no file path for Vivado to lose. Same values as the hex.\n'
         '    initial begin\n' + '\n'.join(l for l in tab.split('\n') if l.strip().startswith('wrom[')) + '\n    end\n')
    out=src[:gs]+inl+src[ge:]
    out=out.replace('module conv_layer #(','module conv_layer_c1 #(')
    # strip the WEIGHT_FILE/BAKED_WEIGHTS parameter block: this variant has no file path
    ps=out.index('    parameter WEIGHT_FILE = "sim/vectors/conv_c1_w.hex",')
    pe=out.index('    parameter IN_BITS  =')
    out=out[:ps]+'    // (no WEIGHT_FILE / BAKED_WEIGHTS: the conv1 table is inlined below)\n'+out[pe:]
    out=out.replace('// still uses $readmemh, which Vivado honours at synthesis if the hex file\n// is added as a project source.','// are INLINED in this generated variant -- nothing for synthesis to find.')
    hdr=('// ============================================================================\n'
         '// GENERATED FILE -- do not edit. Regenerate with:  python3 sim/gen_weight_vh.py\n'
         '// conv_layer.v with the conv1 weight table INLINED, for synthesis: no include,\n'
         '// no $readmemh, no file path for Vivado to lose. sim/run_axis_tb.sh\n'
         '// instantiates this exact module, so the table is verified against golden.\n'
         '// ============================================================================\n')
    open(os.path.join(REPO,'hdl','dense','conv_layer_c1.v'),'w').write(hdr+out)
    print('conv_layer_c1.v: inlined')
import re
emit_inlined_conv1()


# --- self-contained synthesis variant of ed_scatter for c1: W_T inlined ---
def emit_inlined_ed_scatter_c1():
    import numpy as np
    z=np.load(os.path.join(REPO,'golden','m1_weights_int8.npz'))
    wt=np.ascontiguousarray(z['conv1'].transpose(1,2,3,0)).ravel()   # W_T[ic][ky][kx][oc]
    src=open(os.path.join(REPO,'hdl','eventdriven','ed_scatter.v')).read()
    line='    initial $readmemh(WT_FILE, wt);\n'
    gs=src.index(line); ge=gs+len(line)
    inl=('    // W_T INLINED (generated by sim/gen_weight_vh.py): transposed conv1\n'
         '    // table, %d entries, address ((ic*3+ky)*3+kx)*C_OUT+oc. No $readmemh.\n'
         '    initial begin\n' % len(wt) +
         '\n'.join("        wt[%3d] = 8'h%02x;" % (i,int(v)&0xFF) for i,v in enumerate(wt)) + '\n    end\n')
    out=src[:gs]+inl+src[ge:]
    out=out.replace('module ed_scatter #(','module ed_scatter_c1 #(')
    hdr=('// ============================================================================\n'
         '// GENERATED FILE -- do not edit. Regenerate with:  python3 sim/gen_weight_vh.py\n'
         '// ed_scatter.v with the transposed conv1 weight table INLINED, for synthesis.\n'
         '// The AXIS testbench with ENGINE=1 instantiates this exact module.\n'
         '// ============================================================================\n')
    open(os.path.join(REPO,'hdl','eventdriven','ed_scatter_c1.v'),'w').write(hdr+out)
    print('ed_scatter_c1.v: inlined (%d W_T entries)' % len(wt))
emit_inlined_ed_scatter_c1()


# --- r1 (robot-geometry) baked variants, generated only when the real-weight
# vectors exist (P1). Same anchor-replacement approach as the c1 variants:
# conv_layer_r1.v / ed_scatter_r1.v with the DISTILLED quantised weights
# inlined, ready for the next Vivado session's 64x64 bitstream.
def conv1_vals_from_npz(npz_path):
    """The conv1 table in wrom order (oc, ic, ky, kx), from a TRACKED weight
    file. Added 2026-09-19 after sim/vectors/conv_c1_w.hex (untracked, shared
    scratch) was found holding a different network's weights: the baked
    files must derive from git-tracked inputs, never from the scratch hex."""
    import numpy as np
    w = np.load(npz_path)['conv1'].astype(int)
    return ["%02x" % (int(w[oc, ic, ky, kx]) & 0xFF)
            for oc in range(w.shape[0]) for ic in range(w.shape[1])
            for ky in range(3) for kx in range(3)]


def gen_conv_p(name, w_hex_path, npz_path=None):
    """Baked conv_layer_p variant: module conv_layer_p_<name> with the
    weight table inlined (wrom_all), same anchor discipline as the others.
    With npz_path the values come from the tracked file (c1, g1); the hex
    path is only used for r1 (checkpoint-derived, no tracked npz)."""
    if npz_path is not None:
        vals = conv1_vals_from_npz(npz_path)
    else:
        if not os.path.exists(w_hex_path):
            return
        vals = [l.strip() for l in open(w_hex_path) if l.strip()]
    src = open(os.path.join(REPO, 'hdl', 'dense', 'conv_layer_p.v')).read()
    init = ("    // BAKED weights (%s), inlined -- no $readmemh for Vivado to lose\n"
            "    initial begin\n" % name) +         "".join("        wrom_all[%d] = 8'h%s;\n" % (i, v) for i, v in enumerate(vals)) + "    end\n"
    src = src.replace("module conv_layer_p #(", "module conv_layer_p_%s #(" % name)
    src = src.replace("    initial $readmemh(WEIGHT_FILE, wrom_all);\n", init)
    out = os.path.join(REPO, 'hdl', 'dense', 'conv_layer_p_%s.v' % name)
    open(out, 'w').write(src)
    print("conv_layer_p_%s.v: inlined (%d entries)" % (name, len(vals)))


gen_conv_p('c1', None, os.path.join(REPO, 'golden', 'm1_weights_int8.npz'))
gen_conv_p('r1', None, os.path.join(REPO, 'golden', 'r1_student_weights_int8.npz'))
gen_conv_p('g1', None, os.path.join(REPO, 'golden', 'dvsgesture_weights_int8.npz'))   # DVS-Gesture C1 (C0012)


R1_NPZ = os.path.join(REPO, 'golden', 'r1_student_weights_int8.npz')   # tracked (2026-09-19)


def r1_scatter_vals():
    import numpy as np
    wt = np.ascontiguousarray(np.load(R1_NPZ)['conv1'].astype(int).transpose(1, 2, 3, 0)).ravel()
    return ["%02x" % (int(v) & 0xFF) for v in wt]


def gen_r1():
    """r1 (robot geometry, distilled student) baked variants from the TRACKED
    golden/r1_student_weights_int8.npz -- never from sim/vectors, whose r1
    hex is rewritten with SYNTHETIC weights by the ladder's corner check."""
    src = open(os.path.join(REPO, 'hdl', 'dense', 'conv_layer.v')).read()
    vals = conv1_vals_from_npz(R1_NPZ)
    init = "    // DISTILLED r1 weights (P1), inlined -- no $readmemh\n    initial begin\n" + \
        "".join("        wrom[%d] = 8'h%s;\n" % (i, v) for i, v in enumerate(vals)) + "    end\n"
    src = src.replace("module conv_layer #(", "module conv_layer_r1 #(")
    src = src.replace("    initial $readmemh(WEIGHT_FILE, wrom);\n", init)
    open(os.path.join(REPO, 'hdl', 'dense', 'conv_layer_r1.v'), 'w').write(src)
    src = open(os.path.join(REPO, 'hdl', 'eventdriven', 'ed_scatter.v')).read()
    vals = r1_scatter_vals()
    init = "    // DISTILLED r1 W_T (P1), inlined -- no $readmemh\n    initial begin\n" + \
        "".join("        wt[%d] = 8'h%s;\n" % (i, v) for i, v in enumerate(vals)) + "    end\n"
    src = src.replace("module ed_scatter #(", "module ed_scatter_r1 #(")
    src = src.replace("    initial $readmemh(WT_FILE, wt);\n", init)
    open(os.path.join(REPO, 'hdl', 'eventdriven', 'ed_scatter_r1.v'), 'w').write(src)
    print("conv_layer_r1.v / ed_scatter_r1.v: inlined (%d / %d entries)" % (len(conv1_vals_from_npz(R1_NPZ)), len(vals)))


gen_r1()


def gen_scatter(name, wt_hex, note, npz_path=None):
    """Baked ed_scatter variant: module ed_scatter_<name> with W_T inlined.
    With npz_path the table comes from the tracked file (order ic,ky,kx,oc)."""
    if npz_path is not None:
        import numpy as np
        z = np.load(npz_path)
        wt = np.ascontiguousarray(z['conv1'].transpose(1, 2, 3, 0)).ravel()
        import tempfile
        tmp = os.path.join(tempfile.mkdtemp(), 'wt_%s_from_npz.hex' % name)
        open(tmp, 'w').write("".join("%02x\n" % (int(v) & 0xFF) for v in wt))
        wt_hex = tmp
    if not os.path.exists(wt_hex):
        return
    vals = [l.strip() for l in open(wt_hex) if l.strip()]
    src = open(os.path.join(REPO, 'hdl', 'eventdriven', 'ed_scatter.v')).read()
    init = ("    // BAKED W_T (%s), inlined -- no $readmemh for Vivado to lose\n"
            "    initial begin\n" % note) + \
        "".join("        wt[%d] = 8'h%s;\n" % (i, v) for i, v in enumerate(vals)) + "    end\n"
    src = src.replace("module ed_scatter #(", "module ed_scatter_%s #(" % name)
    assert "    initial $readmemh(WT_FILE, wt);\n" in src
    src = src.replace("    initial $readmemh(WT_FILE, wt);\n", init)
    open(os.path.join(REPO, 'hdl', 'eventdriven', 'ed_scatter_%s.v' % name), 'w').write(src)
    print("ed_scatter_%s.v: inlined (%d entries)" % (name, len(vals)))


# DVS-Gesture C1 (C0012): selected on the board by axis_conv_top DATASET=1
gen_scatter('g1', None, 'DVS-Gesture C1, C0012', os.path.join(REPO, 'golden', 'dvsgesture_weights_int8.npz'))
